/**
 * Utility: Create & Publish Example Workflows
 * 
 * Creates the "AI Events Scraper" workflow via the platform API,
 * then publishes it to the marketplace under the logged-in user account.
 * 
 * Usage (from browser console or a page component):
 *   import { createAndPublishAIEventsWorkflow } from '../utils/createExampleWorkflows';
 *   await createAndPublishAIEventsWorkflow();
 */

import * as workflowsApi from '../api/workflows';
// Marketplace service removed — no-op stubs
const createMarketplaceItem = async (..._args: any[]) => ({ id: 'stub' });
const publishMarketplaceListing = async (..._args: any[]) => ({});

// ── AI Events Scraper Workflow Definition ──
const AI_EVENTS_SCRAPER_WORKFLOW = {
  name: 'AI Events Scraper & Report',
  description:
    'Searches the internet for AI/IT events, extracts structured event data using LLM, ' +
    'removes duplicates, generates a professional HTML report, and emails it as a PDF attachment. ' +
    'Customize the search query, recipient email, and report format to fit your needs.',
  trigger_type: 'manual' as const,
  trigger_config: {
    ui_graph: {
      nodes: [
        {
          id: 'start',
          type: 'start',
          label: 'Start',
          position: { x: 50, y: 250 },
          config: {},
        },
        {
          id: 'search_events',
          type: 'web_search',
          label: 'Search AI Events',
          position: { x: 250, y: 250 },
          config: {
            query: 'AI technology conferences events 2026',
            engine: 'duckduckgo',
            max_results: 50,
            time_range: 'month',
            region: 'global',
          },
        },
        {
          id: 'extract_events',
          type: 'llm_completion',
          label: 'Extract Event Data',
          position: { x: 480, y: 250 },
          config: {
            provider: 'groq',
            model: 'groq/llama-3.3-70b-versatile',
            prompt:
              'You are a data extraction expert. Your job is to extract structured event information ' +
              'from raw web search results. Return a JSON array of event objects.',
            user_message:
              'Extract all AI, ML, and IT events from these search results. ' +
              'For each event, return a JSON object with these fields:\n' +
              '- name: Event name\n' +
              '- description: Brief description of the event\n' +
              '- date: Event date (YYYY-MM-DD or range)\n' +
              '- time: Event time or "TBA"\n' +
              '- location: City, Country or "Online"\n' +
              '- price: Ticket price or "Free" or "TBA"\n' +
              '- registration_url: URL to register\n\n' +
              'Search results:\n{{steps.search_events.output}}',
            max_tokens: 4096,
            temperature: 0.2,
          },
        },
        {
          id: 'deduplicate',
          type: 'data_filter',
          label: 'Remove Duplicates',
          position: { x: 710, y: 250 },
          config: {
            field: 'name',
            operator: 'is_unique',
            deduplicate_key: 'name',
          },
        },
        {
          id: 'format_report',
          type: 'llm_completion',
          label: 'Generate HTML Report',
          position: { x: 940, y: 250 },
          config: {
            provider: 'groq',
            model: 'groq/llama-3.3-70b-versatile',
            prompt:
              'You are a professional report designer. Generate a beautiful, modern HTML document ' +
              'suitable for PDF conversion. Use inline CSS for styling. Include a header, table of events, ' +
              'and footer with generation timestamp.',
            user_message:
              'Create a professional HTML report titled "AI & IT Events Report" with:\n' +
              '1. A styled header with the title and current date\n' +
              '2. A summary section with total event count\n' +
              '3. A responsive table with columns: Event Name, Description, Date & Time, Location, Price, Register Link\n' +
              '4. Each registration URL should be a clickable link\n' +
              '5. A footer with "Generated by DevSwat Workflow Engine"\n\n' +
              'Events data:\n{{steps.deduplicate.output}}',
            max_tokens: 4096,
            temperature: 0.4,
          },
        },
        {
          id: 'email_report',
          type: 'email_send',
          label: 'Email Report',
          position: { x: 1170, y: 250 },
          config: {
            to: '{{input.recipient_email}}',
            subject: 'AI & IT Events Report - Generated {{steps.format_report.output.date}}',
            body: '{{steps.format_report.output}}',
            from_name: 'DevSwat Workflows',
            provider: 'platform_smtp',
            attach_output: 'pdf',
          },
        },
        {
          id: 'end',
          type: 'end',
          label: 'Done',
          position: { x: 1380, y: 250 },
          config: {},
        },
      ],
      edges: [
        { id: 'e1', source: 'start', target: 'search_events' },
        { id: 'e2', source: 'search_events', target: 'extract_events' },
        { id: 'e3', source: 'extract_events', target: 'deduplicate' },
        { id: 'e4', source: 'deduplicate', target: 'format_report' },
        { id: 'e5', source: 'format_report', target: 'email_report' },
        { id: 'e6', source: 'email_report', target: 'end' },
      ],
    },
    ui_status: 'published',
    ui_published_at: new Date().toISOString(),
  },
  steps: [
    {
      name: 'search_events',
      type: 'web_search',
      config: {
        query: 'AI technology conferences events 2026',
        engine: 'duckduckgo',
        max_results: 50,
        time_range: 'month',
      },
    },
    {
      name: 'extract_events',
      type: 'llm_completion',
      config: {
        provider: 'groq',
        model: 'groq/llama-3.3-70b-versatile',
        prompt: 'Extract structured event data from search results into a JSON array.',
        user_message: 'Extract AI/IT events. Return JSON with: name, description, date, time, location, price, registration_url. Data: {{steps.search_events.output}}',
        max_tokens: 4096,
        temperature: 0.2,
      },
    },
    {
      name: 'deduplicate',
      type: 'data_filter',
      config: {
        field: 'name',
        operator: 'is_unique',
        deduplicate_key: 'name',
      },
    },
    {
      name: 'format_report',
      type: 'llm_completion',
      config: {
        provider: 'groq',
        model: 'groq/llama-3.3-70b-versatile',
        prompt: 'Generate a professional HTML report for PDF conversion.',
        user_message: 'Create HTML report "AI & IT Events Report" with table: Name, Description, Date, Location, Price, Register Link. Events: {{steps.deduplicate.output}}',
        max_tokens: 4096,
        temperature: 0.4,
      },
    },
    {
      name: 'email_report',
      type: 'email_send',
      config: {
        to: '{{input.recipient_email}}',
        subject: 'AI & IT Events Report',
        body: '{{steps.format_report.output}}',
        provider: 'platform_smtp',
        attach_output: 'pdf',
      },
    },
  ],
};

/**
 * Create the AI Events Scraper workflow via API.
 * Returns the created workflow object.
 */
export const createAIEventsWorkflow = async () => {
  const workflow = await workflowsApi.createWorkflow(AI_EVENTS_SCRAPER_WORKFLOW);
  console.log('[createExampleWorkflows] Created workflow:', workflow.id, workflow.name);
  return workflow;
};

/**
 * Publish a workflow to the marketplace.
 * Creates a marketplace listing and publishes it.
 */
export const publishWorkflowToMarketplace = async (workflowId: string) => {
  // Step 1: Create marketplace listing
  const listing = await createMarketplaceItem({
    name: 'AI Events Scraper & Report',
    description:
      'Automated workflow that searches the internet for AI/IT events, ' +
      'extracts structured data using LLM, removes duplicates, generates a professional ' +
      'HTML/PDF report, and emails it to specified recipients. ' +
      'Fully customizable — change the search query, add filters, modify the report template, ' +
      'or change the email recipient.',
    short_description: 'Scrape AI events from the web, generate PDF report, email it automatically',
    item_type: 'workflow',
    category: 'automation',
    tags: ['ai-events', 'web-scraping', 'report-generation', 'email', 'pdf', 'llm', 'automation'],
    price: 0,
    is_free: true,
    item_data: {
      workflow_id: workflowId,
      node_count: 7,
      step_types: ['web_search', 'llm_completion', 'data_filter', 'email_send'],
      estimated_runtime: '30-60 seconds',
      required_providers: ['groq'],
    },
  });

  console.log('[createExampleWorkflows] Created marketplace listing:', listing.id);

  // Step 2: Publish it
  try {
    const result = await publishMarketplaceListing(listing.id);
    console.log('[createExampleWorkflows] Published to marketplace:', result);
    return { workflow_id: workflowId, listing_id: listing.id, status: 'published' };
  } catch (err) {
    console.warn('[createExampleWorkflows] Listing created but publish failed:', err);
    return { workflow_id: workflowId, listing_id: listing.id, status: 'draft' };
  }
};

/**
 * Full pipeline: Create workflow + Publish to marketplace.
 * Call this from browser console or a component.
 */
export const createAndPublishAIEventsWorkflow = async () => {
  console.log('[createExampleWorkflows] Starting AI Events Scraper workflow creation...');
  
  // Create the workflow
  const workflow = await createAIEventsWorkflow();
  
  // Publish to marketplace
  const result = await publishWorkflowToMarketplace(workflow.id);
  
  console.log('[createExampleWorkflows] Done!', result);
  return result;
};
