import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getSession } from '../../utils/auth';
import { canAccess, type Role } from '../../utils/permissions';
import { fetchMRR, fetchUsage } from '../../api/finance';
import { Button, Card, Text } from '../../components/ui';
import { LoadingState } from '@/components/shared/LoadingState';
import { ErrorState } from '@/components/shared/ErrorState';
import { exportToCSV } from '../../utils/export';
import { goToDashboard } from '../../utils/navigation';
import { ModernPageLayout } from '../../components/layout/ModernPageLayout';
import { logger } from '../../utils/logger';

const ReportsPage = () => {
  const navigate = useNavigate();
  const session = getSession();
  const userRole = session.role as Role | null;
  const [mrr, setMrr] = useState<any>(null);
  const [usage, setUsage] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!canAccess(userRole, 'finance')) {
      goToDashboard(navigate);
      return;
    }

    const load = async () => {
      setLoading(true);
      setError(null);
      try {
        const [mrrData, usageData] = await Promise.all([
          fetchMRR().catch(() => ({ mrr: 0, arr: 0 })),
          fetchUsage().catch(() => ({ total_predictions: 0, api_calls_this_month: 0 })),
        ]);
        setMrr(mrrData);
        setUsage(usageData);
      } catch (err: any) {
        logger.error('Reports load error', err, { component: 'ReportsPage' });
        setError(err?.response?.data?.detail || err?.message || 'Failed to load reports');
      } finally {
        setLoading(false);
      }
    };

    load();
  }, [userRole, navigate]);

  const handleExport = (type: string) => {
    if (type === 'usage') {
      const usageData = [
        {
          'Metric': 'Total Predictions (30 days)',
          'Value': usage?.total_predictions || 0,
          'Date': new Date().toISOString().split('T')[0],
        },
        {
          'Metric': 'API Calls This Month',
          'Value': usage?.api_calls_this_month || 0,
          'Date': new Date().toISOString().split('T')[0],
        },
      ];
      exportToCSV(usageData, 'usage-report');
    } else if (type === 'mrr') {
      const mrrData = [
        {
          'Metric': 'Monthly Recurring Revenue (MRR)',
          'Value (cents)': mrr?.mrr || 0,
          'Value (USD)': mrr?.mrr ? `$${(mrr.mrr / 100).toLocaleString()}` : '$0',
          'Date': new Date().toISOString().split('T')[0],
        },
        {
          'Metric': 'Annual Recurring Revenue (ARR)',
          'Value (cents)': mrr?.arr || 0,
          'Value (USD)': mrr?.arr ? `$${(mrr.arr / 100).toLocaleString()}` : '$0',
          'Date': new Date().toISOString().split('T')[0],
        },
      ];
      exportToCSV(mrrData, 'mrr-report');
    }
  };

  const handleExportReport = () => {
    const reportData = [
      {
        'Report Type': 'Financial Summary',
        'MRR (cents)': mrr?.mrr || 0,
        'MRR (USD)': mrr?.mrr ? `$${(mrr.mrr / 100).toLocaleString()}` : '$0',
        'ARR (cents)': mrr?.arr || 0,
        'ARR (USD)': mrr?.arr ? `$${(mrr.arr / 100).toLocaleString()}` : '$0',
        'Total Predictions (30d)': usage?.total_predictions || 0,
        'API Calls This Month': usage?.api_calls_this_month || 0,
        'Report Date': new Date().toISOString().split('T')[0],
        'Generated By': session.email || 'Unknown',
      },
    ];
    exportToCSV(reportData, 'financial-report');
  };

  if (loading) {
    return <LoadingState message="Loading financial reports..." fullPage />;
  }

  if (error) {
    return (
      <ErrorState
        title="Unable to load reports"
        message={error || 'Failed to load financial reports. Please try again.'}
        onRetry={() => window.location.reload()}
        retryLabel="Retry"
        icon="📊"
      />
    );
  }

  const headerActions = (
    <Button size="md" onClick={handleExportReport}>
      Export Report
    </Button>
  );

  return (
    <ModernPageLayout
      title="Financial Reports & Analytics"
      subtitle="Comprehensive financial reporting with MRR, ARR, usage metrics, and revenue analytics. Export reports for accounting, forecasting, and business intelligence. All financial data includes detailed usage breakdowns and is ready for accounting integration."
      headerActions={headerActions}
      loading={loading}
      error={error}
      onRetry={() => window.location.reload()}
      maxWidth="xl"
    >
      {/* Financial Metrics */}
      <Card variant="elevated" padding="md">
        <Card.Header>
          <Text variant="h2" color="primary" style={{ marginBottom: 'var(--space-2)' }}>
            Key Financial Metrics
          </Text>
          <Text variant="body-sm" color="secondary">
            Key financial metrics showing platform revenue and growth.
          </Text>
        </Card.Header>
        <Card.Body>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: 'var(--space-4)' }}>
            <Card variant="outlined" padding="md">
              <Text variant="body-sm" color="secondary" style={{ marginBottom: 'var(--space-1)' }}>
                Monthly Recurring Revenue (MRR)
              </Text>
              <Text variant="h2" color="primary" style={{ marginBottom: 'var(--space-1)' }}>
                ${mrr?.mrr ? (mrr.mrr / 100).toLocaleString() : '0'}
              </Text>
              <Text variant="caption" color="muted" style={{ marginBottom: 'var(--space-2)' }}>
                As of {new Date().toLocaleDateString()}
              </Text>
              <Text variant="caption" color="muted">
                Total monthly subscription revenue from all active plans
              </Text>
            </Card>
            <Card variant="outlined" padding="md">
              <Text variant="body-sm" color="secondary" style={{ marginBottom: 'var(--space-1)' }}>
                Annual Recurring Revenue (ARR)
              </Text>
              <Text variant="h2" color="primary" style={{ marginBottom: 'var(--space-1)' }}>
                ${mrr?.arr ? (mrr.arr / 100).toLocaleString() : '0'}
              </Text>
              <Text variant="caption" color="muted" style={{ marginBottom: 'var(--space-2)' }}>
                Projected annual
              </Text>
              <Text variant="caption" color="muted">
                Projected annual revenue (MRR × 12) assuming current subscription rates
              </Text>
            </Card>
          </div>

          <Card variant="outlined" padding="md" style={{ marginTop: 'var(--space-4)' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 'var(--space-3)' }}>
              <div>
                <Text variant="body-sm" color="secondary" style={{ marginBottom: 'var(--space-1)' }}>
                  Total Usage (30 days)
                </Text>
            <Text variant="caption" color="muted" style={{ marginBottom: 'var(--space-2)' }}>
              Total predictions processed across all organizations in the last 30 days
            </Text>
                <Text variant="h2" color="primary">
              {usage?.total_predictions || 0}
            </Text>
                <Text variant="caption" color="muted">Predictions</Text>
              </div>
              <Button size="md" onClick={() => handleExport('usage')} variant="secondary">
              Export CSV
            </Button>
            </div>
          </Card>
            </Card.Body>
            </Card>

      {/* Prediction Volume */}
            <Card variant="elevated" padding="md">
              <Card.Header>
          <Text variant="h2" color="primary" style={{ marginBottom: 'var(--space-2)' }}>
            Prediction Volume
          </Text>
                <Text variant="body-sm" color="secondary">
                  Total prediction volume processed in the last 30 days. This metric helps track platform growth, usage patterns, 
                  and resource requirements. Higher volumes may indicate the need for capacity scaling.
                </Text>
              </Card.Header>
              <Card.Body>
                <Text variant="h2" color="primary" style={{ marginBottom: 'var(--space-2)' }}>
                  {usage?.total_predictions || 0}
                </Text>
          <Text variant="body-sm" color="secondary">
            Total predictions in last 30 days
          </Text>
              </Card.Body>
            </Card>
    </ModernPageLayout>
  );
};

export default ReportsPage;
