import React, { useState, useEffect } from 'react';
import { archiveProject } from '@/api/code';
import { logger } from '@/utils/logger';
import styles from './ProjectArchiveDialog.module.css';

interface ProjectArchiveDialogProps {
  isOpen: boolean;
  onClose: () => void;
  onArchived: (projectHash: string) => void;
  projectId?: string;  // Optional - for project-based archiving
  projectPath: string;  // Folder path for folder-based archiving
}

export const ProjectArchiveDialog: React.FC<ProjectArchiveDialogProps> = ({
  isOpen,
  onClose,
  onArchived,
  projectId,
  projectPath,
}) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [previewHash, setPreviewHash] = useState<string | null>(null);
  const [archivedHash, setArchivedHash] = useState<string | null>(null);

  // Generate preview hash when dialog opens
  useEffect(() => {
    if (isOpen) {
      // Generate a preview hash (same logic as backend will use)
      // This is just for display - actual hash is generated by backend
      const identifier = projectId || projectPath;
      const preview = `sha256:${identifier.substring(0, 16)}...`;
      setPreviewHash(preview);
      setArchivedHash(null);
      setError(null);
    }
  }, [isOpen, projectId, projectPath]);

  const handleArchive = async () => {
    setLoading(true);
    setError(null);

    try {
      // Archive by folder_path if it's a folder, otherwise by project_id
      const result = await archiveProject(projectId, projectPath);
      console.log('✅ Archive result:', result);
      
      // Store the actual hash
      setArchivedHash(result.project_hash);
      onArchived(result.project_hash);
      
      // Auto-close after 3 seconds
      setTimeout(() => {
        onClose();
      }, 3000);
    } catch (error: any) {
      logger.error('Failed to archive project', error);
      const errorMessage = error?.response?.data?.message || error?.response?.data?.detail || error?.message || 'Failed to archive project';
      setError(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const copyHash = (hash: string) => {
    navigator.clipboard.writeText(hash).then(() => {
      // Show temporary success message
      const button = document.activeElement as HTMLElement;
      const originalText = button.textContent;
      button.textContent = '✓ Copied!';
      setTimeout(() => {
        button.textContent = originalText;
      }, 2000);
    }).catch((err) => {
      logger.error('Failed to copy hash', err);
      alert('Failed to copy hash. Please copy manually:\n\n' + hash);
    });
  };

  if (!isOpen) return null;

  return (
    <div className={styles.overlay} onClick={onClose}>
      <div className={styles.dialog} onClick={(e) => e.stopPropagation()}>
        <div className={styles.header}>
          <h3>Archive Project</h3>
          <button className={styles.closeButton} onClick={onClose}>×</button>
        </div>
        
        <div className={styles.content}>
          <p className={styles.description}>
            Archive the project <strong>{projectPath}</strong>?
          </p>
          
          <div className={styles.infoBox}>
            <p className={styles.infoTitle}>⚠️ Important:</p>
            <ul className={styles.infoList}>
              <li>The project will be hidden from your working tree</li>
              <li>All files will remain in Hash Sphere for future reference</li>
              <li>You'll receive a Hash Sphere hash to restore later</li>
              <li><strong>Save the hash before closing this dialog!</strong></li>
            </ul>
          </div>

          {archivedHash ? (
            <div className={styles.hashSection}>
              <p className={styles.hashLabel}>Hash Sphere Hash (SAVE THIS!):</p>
              <div className={styles.hashDisplay}>
                <code className={styles.hashCode}>{archivedHash}</code>
                <button
                  className={styles.copyButton}
                  onClick={() => copyHash(archivedHash)}
                  title="Copy hash to clipboard"
                >
                  📋 Copy
                </button>
              </div>
              <p className={styles.successMessage}>
                ✅ Project archived successfully! {archivedHash.length} files archived.
                <br />
                <strong>This dialog will close in 3 seconds...</strong>
              </p>
            </div>
          ) : (
            <div className={styles.hashPreview}>
              <p className={styles.hashLabel}>Hash will be generated after archiving:</p>
              <code className={styles.hashCode}>{previewHash || 'Generating...'}</code>
            </div>
          )}
          
          {error && (
            <div className={styles.error}>
              <strong>Error:</strong> {error}
            </div>
          )}
        </div>
        
        <div className={styles.footer}>
          <button
            className={styles.cancelButton}
            onClick={onClose}
            disabled={loading}
          >
            Cancel
          </button>
          {!archivedHash && (
            <button
              className={styles.archiveButton}
              onClick={handleArchive}
              disabled={loading}
            >
              {loading ? 'Archiving...' : 'Archive Project'}
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

